### PR TITLE
fix: alignment issue #88 #89

### PR DESCRIPTION
**Pull request by unimu-cic**
## Test case 1
```
// Issue #88
A->A.method {
  // [bold, red]Issue #89
  B:async message
}

A.method() {
  B:method
  self() {
    // [bold, red] similar issue
    B:method
  }
}

A->B:message

A->B.method


A->B.method {
  // [red, bold] issue #89
  A:method
}

A->A.method()
```
image

## Test case 2
```
BookLibService.Borrow(id) {
  User = Session.GetUser()
  if(User.isActive) {
    try {
      BookRepository.Update(id, onLoan, User)
      receipt = new Receipt(id, dueDate)
    } catch (BookNotFoundException) {
      ErrorService.onException(BookNotFoundException)
    } finally {
      Connection.close()
    }
  }
  return receipt
}
```

image

## Test case 3
```
Client->SGW."Get order by id" {
  svc.Get(id) {
    new X()
    rep."load order" {
      =="Start Here"==
      MF."load order from mainframe"
      =="End Here"==
      if(order == null) {
        @return 
        SGW->Client:404
      } else {
        return order
      }
      
      while(true) {
        svc.refresh(data)
      }
      processOrder()
    }
    return order
  }
  return response
}
```
image

## Test case 4
```
// This is a sample
A.do() {
  if (condition1) {
    X.doSomething()
  } else if (condition2) {
    Y.doSomethingElse
  } else {
    doNothing()
  }
}
```
image

## Test case 5
```
// This is a sample
A.method() {
  if(condition) {
    B.method()
  }
}
```
image

### CODE REVIEW

**Comment by MrCoder** [comment]
Edge case:
SCR-20231128-tlil

**Comment by MrCoder** [comment]
The following DSL could be used as a one-for-all example.

```
// comments at the beginning should be ignored
title This is a title
@Lambda <<stereotype>> ParticipantName
group "B C" {@EC2 B @ECS C}
"bg color" #FF0000
@Starter("ParticipantName")
new B
ReturnType ret = ParticipantName.methodA(a, b) {
  // Customised style for RESTFul API - `POST /order` <br>
  ReturnType ret2 = selfCall() {
    B.syncCallWithinSelfCall() {
      ParticipantName.rightToLeftCall()
      return B
    }
    "space in name"->"bg color".syncMethod(from, to)
  }
  // A comment for alt
  if (condition) {
    // A comment for creation
    ret = new CreatAndAssign()
    "ret:CreatAndAssign".method(create, and, assign)
    // A comment for async self
    B->B: Self Async
    // A comment for async message
    B->C: Async Message within fragment
    new Creation() {
      return from_creation
    }
    return "from if to original source"
    try {
      new AHasAVeryLongNameLongNameLongNameLongName() {
        new CreatWithinCreat()
        C.rightToLeftFromCreation() {
          B.FurtherRightToLeftFromCreation()
        }
      }
    } catch (Exception) {
      self {
        return C
      }
    } finally {
      C: async call from implied source  
    }
    =====divider can be anywhere=====
  } else if ("another condition") {
    par {
      B.method
      C.method
    }
  } else {
    // A comment for loop
    forEach(Z) {
      Z.method() {
        return Z
      }
    }
  }
}
```

**Comment by unimu-cic** [comment]
// test-2
A.method() {
  B.method() {
    // 向上到 A.method()
    A:async
  }
}

**Comment by unimu-cic** [comment]
All the above edge cases are fixed, except the largest DSL.
```
A->A.method() {
	B.method() {
    	A.method
    }
}

if(condition) {
	A->A.method
}

A->A.method {
	B.method
}

A->A.method {
	B->C.method
}

A.method() {
	B.method() {
    	A:method
    }
}

// Issue #88
A->A.method {
  // [bold, red]Issue #89
  B:async message
}

A.method() {
  B:method
  self() {
    // [bold, red] similar issue
    B:method
  }
}

A->B:message

A->B.method

A->B.method {
  // [red, bold] issue #89
  A:method
}
```
image

**Comment by MrCoder** [comment]
https://github.com/mermaid-js/zenuml-core/pull/98/checks?check_run_id=19306753996 This check failed.

**Comment by MrCoder** [comment]
# case 1: occurrence not perfectly aligned with the lifeline
```
@Starter(A)
new B
```
image

# case 2: messages with "ProvidedFrom"
```
A B C
A.method1 {
  C->B.syncMethodRightToLeft
  C->B:asyncMethodRightToLeft
  // [green] OK
  C->D.syncMethodLeftToRight
  C->D:asyncMethodLeftToRight
}
```
image

**Review by MrCoder — CHANGES_REQUESTED** [review]
Added 2 cases that should be fixed.

**Pull request merged**
